### ISSUE TITLE
Discovery exits because of segmentation violation

### ISSUE THREAD

**Issue by rahafrouz** [smartfog/fogflow#23]
Hi!
I am Running the components as mentioned in the tutorial. After submitting a fog function, discovery exits. Here is the log before termination:
```
DEBUG: 2019/02/19 22:49:10 repository.go:320: SELECT entity_tab.eid, entity_tab.type, entity_tab.ispattern, entity_tab.providerurl FROM entity_tab  WHERE entity_tab.type like 'Topology'
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x72729c]

goroutine 459 [running]:
main.(*FastDiscovery).sendNotify(0xc000048280, 0xc000148570, 0x24, 0xc00005ac80, 0x37, 0xc0003bb440, 0x7fc2d9, 0x6)
	/Users/cheng/work/go/src/github.com/smartfog/fogflow/discovery/fastDiscovery.go:294 +0x51c
main.(*FastDiscovery).handleSubscrieCtxAvailability(0xc000048280, 0xc000176750)
	/Users/cheng/work/go/src/github.com/smartfog/fogflow/discovery/fastDiscovery.go:242 +0xfc
created by main.(*FastDiscovery).SubscribeContextAvailability
	/Users/cheng/work/go/src/github.com/smartfog/fogflow/discovery/fastDiscovery.go:235 +0x21f
```

Tell me what kind of information is needed to provide so that you reproduce the error.

**Comment by smartfog** [comment]
Could you share how you submit the fog function? Did you define it via the FogFlow dashboard? did you follow this [tutorial](doc/tutorial/fogflow.md)?

**Comment by rahafrouz** [comment]
I used the documentation at the read-the-doc. 
I just read this tutorial and in your link it is mentioned that Orion Broker has to be installed separately. 
I did as instructed in the link you sent, but where should we configure IP of Orion in the Fogflow? 
Also, how is Orion different than internal broker of Fogflow?

Thanks

**Comment by smartfog** [comment]
Sorry, I could not reproduce your problem. 
for Step 2: how did you annotate your fog function via the fog function editor?
for Step 3: did you create the sensor via the dashboard like what we illustrated in the [tutorial](https://github.com/smartfog/fogflow/blob/master/doc/tutorial/fogflow.md)? 

The internal broker in FogFlow follows the standard of NGSI v1. But Orion is based on v2. In the near future, they will all move to the new standard NGSI-LD. 

the problem might be caused by your configuration. when you start FogFlow, you need to change the configuration file config.js accordingly. please check the following IPs in the configuration file. 

webportal_ip: this is the IP address to access the FogFlow web portal provided by Task Designer. It must be accessible from outside by user's browser.
coreservice_ip: it is used by all edge nodes to access the FogFlow core services, including Discovery, Broker(Cloud), and RabbitMQ;
external_hostip: this is the same as coreservice_ip, for the cloud part of FogFlow;
internal_hostip: is the IP of your default docker bridge, which is the "docker0" network interface on your host

the IP of your Orion should be the ip of your VM if you set up Orion Broker on the same VM. However, the IP should be accessible from a docker container. so DO NOT use "127.0.0.1".

**Comment by smartfog** [comment]
I assume that the problem has been addressed. If still not, please contact us and we can help you.
