### ISSUE TITLE
Issue with Unsubscribe : passing of blank data

### ISSUE THREAD

**Issue by pradumnnec** [smartfog/fogflow#296]
While deleting an entity, if a task is associated to it then it is also unsubscribed. This flow is passing blank data.

Work is in progress and soon it would be fixed.

**Comment by showersky** [comment]
Hi Pradumn, 

I have to say that this is not a bug. This is designed for some specific purpose. When receiving an notification with empty payload, we should consider that the corresponding entity is deleted. 

Because there is no such semantic defined by NGSI, we use this special case to represent the removal of an existing entity.

**Comment by Neeraj-Nec** [comment]
Hi bin ,

In ngsild nil notification is not acceptable

**Comment by Neeraj-Nec** [comment]
resolved
