### ISSUE TITLE
Build does not work

### ISSUE THREAD

**Issue by Glagnar** [smartfog/fogflow#6]
PLEASE update your docker files, so the build process is contained within the docker containers.
You can find examples here:
https://docs.docker.com/develop/develop-images/multistage-build/

It is very easy.

**Comment by showersky** [comment]
Thanks for your suggestion, but I am not convinced that this is really necessary for us. If people like to contribute to the development of fogflow, they need to set up a local environment to build the code. Including the build process into a container environment is not faster, since we have to repeat the build process quite frequently during the development phase. For the people who just need to deploy fogflow and try it out, they do not need to build it and they can just set up the entire system using the provided docker images.
